spring:
  application:
    name: blog-oauth2

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "$2a$12$vsisQLhmU9H.LlpR4sLNO.41lUk0fiici62lJaLebEquJLIpzedWy"
              client-authentication-methods:
                - "client_secret_post"
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:1680/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
                - "email"
                - "address"
            require-authorization-consent: true

  datasource:
    url: jdbc:postgresql://128.199.137.87:2345/oauth2
    username: seu
    password: 123
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
  servlet:
    context-path: /identity

logging:
  level:
    org:
      springframework:
        security: DEBUG
